/**
 * Supabase Database Types
 *
 * This file will be auto-generated by `supabase gen types typescript`
 * once the database schema is set up. For now, we define the shape
 * so that all Supabase client code is properly typed.
 *
 * Agent 2 (Database) will generate the full types from the actual schema.
 */

export type UserRole = "admin" | "trucker" | "customer";

export type DeliveryStatus =
  | "pending"
  | "assigned"
  | "in_transit"
  | "delivered"
  | "confirmed"
  | "disputed";

export type InvoiceStatus =
  | "draft"
  | "sent"
  | "viewed"
  | "partial"
  | "paid"
  | "overdue"
  | "void";

export type PaymentMethod = "check" | "ach" | "credit_card" | "cash";

export type MaterialType = "mason_sand" | "cushion_sand" | "other";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          role: UserRole;
          full_name: string;
          phone: string | null;
          company_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      // Additional tables will be defined by Agent 2
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: UserRole;
      delivery_status: DeliveryStatus;
      invoice_status: InvoiceStatus;
      payment_method: PaymentMethod;
      material_type: MaterialType;
    };
  };
}
